#ifndef vtkFluidMapperThicknessAndVolumeColorFilterFS_h
#define vtkFluidMapperThicknessAndVolumeColorFilterFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkFluidMapperThicknessAndVolumeColorFilterFS;

#endif
