#include "vtkOrderIndependentTranslucentPassFinalFS.h"

const char *vtkOrderIndependentTranslucentPassFinalFS =
"//VTK::System::Dec\n"
"\n"
"/*=========================================================================\n"
"\n"
"  Program:   Visualization Toolkit\n"
"  Module:    vtkDepthPeelingPassFinalFS.glsl\n"
"\n"
"  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen\n"
"  All rights reserved.\n"
"  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.\n"
"\n"
"     This software is distributed WITHOUT ANY WARRANTY; without even\n"
"     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR\n"
"     PURPOSE.  See the above copyright notice for more information.\n"
"\n"
"=========================================================================*/\n"
"\n"
"in vec2 texCoord;\n"
"\n"
"uniform sampler2D translucentRTexture;\n"
"uniform sampler2D translucentRGBATexture;\n"
"\n"
"// the output of this shader\n"
"//VTK::Output::Dec\n"
"\n"
"void main()\n"
"{\n"
"  vec4 t1Color = texture(translucentRGBATexture, texCoord);\n"
"  float t2Color = texture(translucentRTexture, texCoord).r;\n"
"\n"
"  gl_FragData[0] = vec4(t1Color.rgb/max(t2Color,0.01), t1Color.a);\n"
"  // gl_FragData[0] = vec4(t1Color.a, t1Color.a, t1Color.a, 0.0);\n"
"  // gl_FragData[0] = vec4(t2Color, t2Color, t2Color, 0.0);\n"
"}\n"
"";
