#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#import gmsh
runApplication gmshToFoam cube2.msh
#combine prisms to polyhedrals
runApplication polyDualMesh 75 -overwrite
#delete the unnecessary 2nd layer
runApplication setSet -batch splitMesh.setSet
runApplication subsetMesh c0 -overwrite -patch front
#fix the mesh
runApplication combinePatchFaces 180 -overwrite
#fix the boundary
python setPatches.py

touch `basename $PWD`.foam

checkMesh
